package laiba_44146;

import javax.swing.ImageIcon;

public class AddCustomerGUI extends javax.swing.JFrame {


	    public AddCustomerGUI() {
	        initComponents();
	        ImageIcon img = new ImageIcon("src/media/makeup.jpg");
	       this.setIconImage(img.getImage());
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        lblWelcomeAdminPanel = new javax.swing.JLabel();
	        lblCustomerUsername = new javax.swing.JLabel();
	        txtCustomerUsername = new javax.swing.JTextField();
	        jLabel9 = new javax.swing.JLabel();
	        txtAddress = new javax.swing.JTextField();
	        jLabel10 = new javax.swing.JLabel();
	        txtSetPassword = new javax.swing.JTextField();
	        cbGender = new javax.swing.JComboBox<>();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel13 = new javax.swing.JLabel();
	        txtPhoneNo = new javax.swing.JTextField();
	        btnRegister = new javax.swing.JButton();
	        jPanel2 = new javax.swing.JPanel();
	        lblDashboard = new javax.swing.JLabel();
	        lblPendingReport = new javax.swing.JLabel();
	        lblDailyReport = new javax.swing.JLabel();
	        lblWeeklyReport = new javax.swing.JLabel();
	        lblSignout = new javax.swing.JLabel();
	        lblExit = new javax.swing.JLabel();
	        jLabel1 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Admin Panel");
	        setResizable(false);
	        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	        jPanel1.setBackground(new java.awt.Color(0, 0, 0,70));

	        lblWelcomeAdminPanel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
	        lblWelcomeAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
	        lblWelcomeAdminPanel.setText("                                                   Add Customer");

	        lblCustomerUsername.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblCustomerUsername.setForeground(new java.awt.Color(255, 255, 255));
	        lblCustomerUsername.setText("Customer userName:");

	        txtCustomerUsername.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                txtCustomerUsernameActionPerformed(evt);
	            }
	        });

	        jLabel9.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel9.setText("Address:");

	        jLabel10.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel10.setText("Set password:");

	        cbGender.setBackground(new java.awt.Color(211, 27, 27,80));
	        cbGender.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
	        cbGender.setForeground(new java.awt.Color(255, 255, 255));
	        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
	        cbGender.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cbGenderActionPerformed(evt);
	            }
	        });

	        jLabel12.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel12.setText("Gender:");

	        jLabel13.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel13.setText("phone no.:");

	        btnRegister.setBackground(new java.awt.Color(197, 14, 14));
	        btnRegister.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
	        btnRegister.setText("Register");
	        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                btnRegisterMouseClicked(evt);
	            }
	        });
	        btnRegister.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnRegisterActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(201, 201, 201)
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(lblCustomerUsername))
	                        .addGap(53, 53, 53)
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
	                            .addComponent(txtCustomerUsername)
	                            .addComponent(txtSetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
	                            .addComponent(cbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(348, 348, 348)
	                        .addComponent(btnRegister)))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(lblCustomerUsername)
	                    .addComponent(txtCustomerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(28, 28, 28)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel9))
	                .addGap(39, 39, 39)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel10)
	                    .addComponent(txtSetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(34, 34, 34)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel12)
	                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(34, 34, 34)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel13)
	                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
	                .addComponent(btnRegister)
	                .addGap(148, 148, 148))
	        );

	        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 890, 610));

	        jPanel2.setBackground(new java.awt.Color(204, 22, 22));

	        lblDashboard.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
	        lblDashboard.setText("Dashboard");
	        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                lblDashboardMouseClicked(evt);
	            }
	        });

	        lblPendingReport.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblPendingReport.setForeground(new java.awt.Color(255, 255, 255));
	        lblPendingReport.setText("Pending orders");
	        lblPendingReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

	        lblDailyReport.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblDailyReport.setForeground(new java.awt.Color(255, 255, 255));
	        lblDailyReport.setText("Daily Report");
	        lblDailyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

	        lblWeeklyReport.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblWeeklyReport.setForeground(new java.awt.Color(255, 255, 255));
	        lblWeeklyReport.setText("Weekly Report");
	        lblWeeklyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        lblWeeklyReport.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                lblWeeklyReportMouseClicked(evt);
	            }
	        });

	        lblSignout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblSignout.setForeground(new java.awt.Color(255, 255, 255));
	        lblSignout.setText("Sign out");
	        lblSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        lblSignout.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                lblSignoutMouseClicked(evt);
	            }
	        });

	        lblExit.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        lblExit.setForeground(new java.awt.Color(255, 255, 255));
	        lblExit.setText("Exit");
	        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                lblExitMouseClicked(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(35, 35, 35)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblPendingReport, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblDailyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblWeeklyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(55, 55, 55)
	                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(lblPendingReport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(lblDailyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(lblWeeklyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(lblSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(183, Short.MAX_VALUE))
	        );

	        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 610));

	        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Third Sem\\Assignments\\Assignment_of_JAVA\\icons\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
	        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>//GEN-END:initComponents

	    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_cbGenderActionPerformed

	    private void txtCustomerUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerUsernameActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_txtCustomerUsernameActionPerformed

	    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
	        // TODO add your handling code here:
	        AdminDashboard ad = new AdminDashboard();
	        ad.setVisible(true);
	        this.setVisible(false);
	    }//GEN-LAST:event_lblDashboardMouseClicked

	    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
	        // TODO add your handling code here:
	        int res;
	        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
	        System.out.println(res);
	        if (res == 0){
	            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
	        }
	       
	    }//GEN-LAST:event_lblExitMouseClicked

	    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
	        // TODO add your handling code here:
	        
	    }//GEN-LAST:event_btnRegisterActionPerformed
	    public void setData(){
	        AddCustomer acb = new AddCustomer();
	        AddCustomerFile acd = new AddCustomerFileImpl();
	        String username = txtCustomerUsername.getText();
	        String address = txtAddress.getText();
	        String password = txtSetPassword.getText();
	        String gender = cbGender.getSelectedItem().toString();
	        String contactNo = txtPhoneNo.getText();
	        acb.setUsername(username);
	        acb.setAddress(address);
	        acb.setPassword(password);
	        acb.setGender(gender);
	        acb.setContactNo(contactNo);
	        acd.writeFile(acb);
	        
	    }
	    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
	        // TODO add your handling code here:
	        if(!"".equals(txtCustomerUsername.getText()) && !txtAddress.getText().equals("")  && !"".equals(txtPhoneNo.getText()) && !"".equals(txtSetPassword.getText()) ){
	            setData();
	            JOptionPane.showMessageDialog(this, "Customer Registered Successfully....");
	            txtCustomerUsername.setText(null);
	            txtAddress.setText(null);
	            txtSetPassword.setText(null);
	            txtPhoneNo.setText(null);
	     
	        }
	        else{
	            JOptionPane.showMessageDialog(this, "Please Fill all fields.");
	        }
	        
	        
	        
	    }

	    private void lblSignoutMouseClicked(java.awt.event.MouseEvent evt) {
	        // TODO add your handling code here:
	        LoginType lt = new LoginType();
	        int res;
	        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
	        switch (res) {
	            case 0:
	                
	                lt.setVisible(true);    
	                this.setVisible(false);     
	                break;
	       
	            default:
	                break;
	        }
	    }

	    private void lblWeeklyReportMouseClicked(java.awt.event.MouseEvent evt) {
	       
	    }

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        
	        java.awt.EventQueue.invokeLater(() -> {
	            new AddCustomer().setVisible(true);
	        });
	    }

	    
	    private javax.swing.JButton btnRegister;
	    private javax.swing.JComboBox<String> cbGender;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JLabel lblCustomerUsername;
	    private javax.swing.JLabel lblDailyReport;
	    private javax.swing.JLabel lblDashboard;
	    private javax.swing.JLabel lblExit;
	    private javax.swing.JLabel lblPendingReport;
	    private javax.swing.JLabel lblSignout;
	    private javax.swing.JLabel lblWeeklyReport;
	    private javax.swing.JLabel lblWelcomeAdminPanel;
	    private javax.swing.JTextField txtAddress;
	    private javax.swing.JTextField txtCustomerUsername;
	    private javax.swing.JTextField txtPhoneNo;
	    private javax.swing.JTextField txtSetPassword;
}
