package laiba_44146;

import laiba_44146.AdminLogin;
import laiba_44146.AdminLoginFile;
import laiba_44146.AdminLoginFileImpl;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AdminLoginGUI extends javax.swing.JFrame {
	    
	    AdminLogin al = new AdminLogin();
	    AdminLoginFile alf = new AdminLoginFileImpl();
	    AdminDashboard ad = new AdminDashboard();

	   
	    public AdminLoginGUI() {
	        initComponents();
	        ImageIcon img = new ImageIcon("src/media/download(1).jpg");
	       this.setIconImage(img.getImage());
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        lblLogin = new javax.swing.JLabel();
	        jLabel1 = new javax.swing.JLabel();
	        txtUsername = new javax.swing.JTextField();
	        jLabel2 = new javax.swing.JLabel();
	        txtPassword = new javax.swing.JPasswordField();
	        btnLoginAdmin = new javax.swing.JButton();
	        jPanel1 = new javax.swing.JPanel();
	        lblBgImage = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Admin Login");
	        setMaximumSize(new java.awt.Dimension(1070, 611));
	        setMinimumSize(new java.awt.Dimension(1070, 611));
	        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	        lblLogin.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
	        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
	        lblLogin.setText("Login");
	        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

	        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel1.setText("Username:");
	        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

	        txtUsername.setBackground(new java.awt.Color(5, 110, 163,70));
	        txtUsername.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
	        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
	        txtUsername.setToolTipText("Enter username");
	        txtUsername.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                txtUsernameActionPerformed(evt);
	            }
	        });
	        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 170, 30));

	        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel2.setText("Password:");
	        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

	        txtPassword.setBackground(new java.awt.Color(5, 110, 163,70));
	        txtPassword.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
	        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
	        txtPassword.setToolTipText("Enter Password");
	        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 170, 30));

	        btnLoginAdmin.setBackground(new java.awt.Color(41, 10, 126));
	        btnLoginAdmin.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
	        btnLoginAdmin.setForeground(new java.awt.Color(255, 255, 255));
	        btnLoginAdmin.setText("Login");
	        btnLoginAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnLoginAdminActionPerformed(evt);
	            }
	        });
	        getContentPane().add(btnLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

	        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
	        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
	        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 370, 380));

	        lblBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/admin login background.jpg"))); // NOI18N
	        getContentPane().add(lblBgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

	        setSize(new java.awt.Dimension(1086, 650));
	        setLocationRelativeTo(null);
	    }// </editor-fold>//GEN-END:initComponents
	    private String Usernamefinal;
	    private String passwordfinal;
	    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_txtUsernameActionPerformed

	    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
	        // TODO add your handling code here:
	        Usernamefinal = txtUsername.getText();
	        passwordfinal = txtPassword.getText();
	       
	        al.setUsername(Usernamefinal);
	        al.setPassword(passwordfinal); 

	        if ( alf.userCredentials(al)== true){
	            JOptionPane.showMessageDialog(this, "Successfully Logged In as an Admin");
	            ad.setVisible(true);
	            this.setVisible(false);
	        }
	        else{
	            JOptionPane.showMessageDialog(this, "Access Denied!! Wrong Credentials. Try Again....");
	            txtUsername.setText(null);
	            txtPassword.setText(null);
	            
	        }
	    }//GEN-LAST:event_btnLoginAdminActionPerformed


	    public static void main(String args[]) {
	        
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new AdminLogin().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton btnLoginAdmin;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JLabel lblBgImage;
	    private javax.swing.JLabel lblLogin;
	    private javax.swing.JPasswordField txtPassword;
	    private javax.swing.JTextField txtUsername;

}
